// <auto-generated />
namespace SystemeGestionEtudiants.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Lamine1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Lamine1));
        
        string IMigrationMetadata.Id
        {
            get { return "202503021954425_Lamine1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
